### ISSUE TITLE
avoid recompile regex by caching

### ISSUE THREAD

**Issue by jerome-laforge** [moov-io/rtp20022#45]
Hello,
Is it possible to avoid to recompile regex each time you want to validate the message?
We can use cache protected by mutex like openapi https://github.com/go-openapi/validate/blob/194d97ec43681857f9279b7c36eed18c8c70e7a1/rexp.go#L26C54-L26C54

Thx in adv
Best

**Comment by adamdecaf** [comment]
Good call, added in https://github.com/moov-io/rtp20022/pull/46
