### ISSUE TITLE
rtp.ISODateTime marshal with RFC3339 layout

### ISSUE THREAD

**Issue by jerome-laforge** [moov-io/rtp20022#47]
Hello,
When I marshal rtp.ISODateTime type, I have something like `2006-01-02T15:04:05` .
But it seems that we need to export with RFC3339 layout.

Do you think that it is possible do to define somewhere the time format that we want to use for marshaling?

Thx in adv for you support.

**Comment by adamdecaf** [comment]
Your XML specs require RFC3339? We found with TCH that they don't support RFC3339.

**Comment by adamdecaf** [comment]
When we've gone through testing for RTP with TCH we found the sub-second precision and timezone format was not accepted. We had to format timestamps as ISO 8601 in order to be accepted.

**Comment by jerome-laforge** [comment]
Ok, that makes sens, but I don't want to change the default timestamp format.
Is it possible for you that define a global public variable with default format as ISO8601?
With this variable, I will be able to define the format (RFC3339 or something else) in order to marshall/unmarshall the ISODateTime.

**Comment by jerome-laforge** [comment]
I use it for BCEAO zone (https://en.wikipedia.org/wiki/Central_Bank_of_West_African_States)

**Comment by jerome-laforge** [comment]
FYI, I regenerate the model/validate with specific xsd and modified template.

**Comment by adamdecaf** [comment]
Did you figure out if you needed more changes? Or if a fork of rtp20022 would be your solution?

**Comment by jerome-laforge** [comment]
Thank again for your support :pray: 
For now based on the provided examples, the fork works fine with the modifications on:
- date layout
- precision for amount (#49) 

I would have preferred that those 2 modifications were merged in the upstream (with the default values that allow keep current behavior for TCH). If those 2 modifications have been merged then I will be able to remove `replace github.com/moov-io/rtp20022 v0.9.4 => github.com/jerome-laforge/rtp20022 v0.0.0-20231208075226-8e7a6baf36f9` directive from our go.mod.

**Comment by adamdecaf** [comment]
I'm not sure we want to maintain extensible support for ISO 20022 and all of its various implementations. TCH makes a lot of changes to the ISO 20022 spec which are not compatible with BCEAO. We will help you stay updated with the generated code.

**Comment by adamdecaf** [comment]
I appreciate your insight with understanding there are slight differences in ISO 20022 usages across the industry. We are seeing this with [fednow](https://github.com/moov-io/fednow20022) and [fedwire](https://github.com/moov-io/fedwire20022) implementations of ISO 20022 as well.
