### ISSUE TITLE
rtp.Amount trim trailing zero (or not force the decimal part)

### ISSUE THREAD

**Issue by jerome-laforge** [moov-io/rtp20022#49]
Hello,
Is it possible to not force the decimal part of `rtp.Amount`?
Because some currencies:
- don't have decimal part (i.e. XOF, XAF) 
- have more than 2 digits on decimal part (more unusual...)

**Comment by adamdecaf** [comment]
This repository is used for RTP (by The Clearing House) which only allows USD. They don't support all of the currencies that ISO 20022 does.

**Comment by jerome-laforge** [comment]
make sens, but it possible to define global variable for precision of amount (as for ISODate https://github.com/jerome-laforge/rtp20022/commit/ac6fa8700c64570bc8c2e0866f2fc66affd78e50) with default value set to 2 (current behavior for USD) ?
```go
	f := 1.5
	fmt.Println(strconv.FormatFloat(f, 'f', -1, 64)) // 1.5 no trailling zeros
	fmt.Println(strconv.FormatFloat(f, 'f', 2, 64))  // 1.50 
	fmt.Println(strconv.FormatFloat(f, 'f', 3, 64))  // 1.500
```

https://go.dev/play/p/wQUjk5C34-5

**Comment by adamdecaf** [comment]
I appreciate your insight with understanding there are slight differences in ISO 20022 usages across the industry. We are seeing this with [fednow](https://github.com/moov-io/fednow20022) and [fedwire](https://github.com/moov-io/fedwire20022) implementations of ISO 20022 as well.
